# Lista personalizzata di Stopwords per l'analisi di pattern testuali (Versione 5 - Definitiva e Corretta)
# Criterio: Esclusione di termini strutturali, grammaticali, di processo/azione, 
# procedure di imaging/laboratorio, e misure/descrittori generici ad alta frequenza.
# Sono stati MANTENUTI: nomi di sintomi, reperti anatomici/patologici specifici (es. 'tumor', 'pain', 'fever', 'liver', 'artery', etc.).

cust_sw = {
    # Termini Originali (Consolidati)
    'able', 'about', 'above', 'accomplish', 'accord', 'achieve', 'action', 'activity', 
    'acute', 'adequately', 'administration', 'adverse', 'agent', 'ago', 'aim', 'along', 
    'although', 'also', 'always', 'among', 'another', 'anterior', 'any', 'appear', 
    'appearance', 'apparent', 'apply', 'approach', 'appropriately', 'approximately', 
    'around', 'aspect', 'ask', 'assessment', 'associate', 'assume', 'attempt', 'aware', 
    'bad', 'baseline', 'before', 'begin', 'being', 'believe', 'below', 'beneath', 'best', 
    'between', 'beyond', 'big', 'bilateral', 'black', 'blue', 'body', 'both', 'boy', 
    'bring', 'but', 'by', 'call', 'can', 'care', 'carry', 'case', 'cause', 'cavity', 
    'cease', 'center', 'central', 'challenge', 'chance', 'change', 'characteristic', 
    'child', 'choose', 'chronic', 'clean', 'clear', 'clinic', 'closed', 'cold', 'come', 
    'common', 'committee', 'compare', 'complete', 'complication', 'component', 'complex', 
    'confirm', 'consequence', 'consider', 'consist', 'consultation', 'contain', 
    'content', 'continue', 'continuously', 'contrast', 'cool', 'could', 'course', 
    'criterion', 'current', 'currently', 'daily', 'danger', 'data', 'day', 'decide', 
    'decrease', 'decreased', 'deep', 'degree', 'demonstrate', 'deny', 'department', 
    'describe', 'despite', 'detail', 'determine', 'develop', 'diagnosis', 'diastolic', 
    'die', 'different', 'difficult', 'diffuse', 'directly', 'dirty', 'discharge', 
    'disease', 'disappear', 'distal', 'dl', 'do', 'does', 'dose', 'dosing', 'double', 
    'drug', 'dry', 'during', 'duration', 'each', 'early', 'easier', 'easily', 'easy', 
    'effect', 'elevated', 'elevate', 'element', 'episode', 'especially', 'eventually', 
    'every', 'evidence', 'examination', 'except', 'expect', 'experience', 'explain', 
    'extend', 'extensive', 'external', 'extent', 'fact', 'factor', 'fail', 'fall', 
    'family', 'far', 'fashion', 'father', 'feature', 'feel', 'few', 'field', 'final', 
    'find', 'finding', 'finish', 'fluid', 'focal', 'focus', 'follow', 'followup', 
    'forget', 'form', 'fragment', 'frequently', 'from', 'full', 'fully', 'function', 
    'furthermore', 'gain', 'general', 'get', 'give', 'go', 'goal', 'good', 'gradually', 
    'grade', 'great', 'green', 'grow', 'growth', 'had', 'happen', 'hard', 'has', 'have', 
    'having', 'he', 'hear', 'heavy', 'help', 'hence', 'her', 'high', 'history', 'hold', 
    'home', 'hope', 'hospital', 'hot', 'hour', 'how', 'however', 'impact', 'improve', 
    'in', 'include', 'including', 'increase', 'increased', 'index', 'indicate', 
    'inferior', 'inform', 'information', 'initial', 'initiate', 'initially', 'institution', 
    'intend', 'internal', 'intermittently', 'involve', 'issue', 'job', 'keep', 'kg', 
    'kind', 'know', 'known', 'later', 'lateral', 'layer', 'lead', 'learn', 'least', 
    'leave', 'left', 'leg', 'lesion', 'less', 'let', 'level', 'lie', 'light', 'like', 
    'limit', 'line', 'little', 'local', 'location', 'long', 'look', 'lower', 'mainly', 
    'maintain', 'male', 'manage', 'manner', 'many', 'marked', 'mass', 'material', 'may', 
    'mechanism', 'medial', 'medical', 'method', 'mg', 'middle', 'might', 'mild', 
    'minimal', 'minute', 'ml', 'mm', 'mmhg', 'moderate', 'monitor', 'month', 'monthly', 
    'more', 'moreover', 'most', 'mother', 'move', 'much', 'multiple', 'must', 'nature', 
    'nearly', 'need', 'negative', 'new', 'next', 'no', 'node', 'non', 'nor', 'normal', 
    'not', 'notice', 'now', 'number', 'nand', 'nas', 'nat', 'nbefore', 'nbeing', 'nboth', 
    'nbut', 'nby', 'ncan', 'ncomputed', 'ncould', 'ndid', 'ndo', 'ndoes', 'ndue', 
    'nduring', 'neach', 'nfor', 'nfrom', 'nhad', 'nhas', 'nhave', 'nhaving', 'nhe', 
    'nher', 'nhow', 'nin', 'nlaboratory', 'nmay', 'nmight', 'nmore', 'nmost', 'nnot', 
    'nonly', 'nor', 'nother', 'nown', 'npatient', 'nphysical', 'nsame', 'nshall', 
    'nshould', 'nso', 'nsome', 'nsuch', 'nthan', 'nthe', 'nthere', 'nthis', 'nto', 
    'ntoo', 'nuntil', 'ntwo', 'nusual', 'nvery', 'nwas', 'nwe', 'nwere', 'nwhere', 'nwhich', 
    'nwho', 'nwhy', 'nwill', 'nwith', 'nwould', 'object', 'objective', 'obtain', 
    'observe', 'obvious', 'occasionally', 'occur', 'often', 'old', 'one', 'only', 
    'onset', 'open', 'operation', 'opportunity', 'organization', 'other', 'outcome', 
    'over', 'overall', 'own', 'partially', 'particularly', 'parent', 'parameter', 'part', 
    'partial', 'past', 'pathology', 'pattern', 'per', 'perform', 'peripheral', 'period', 
    'persistently', 'person', 'piece', 'place', 'plan', 'point', 'poor', 'portion', 
    'position', 'positive', 'possibility', 'possible', 'post', 'potential', 'prefer', 
    'presence', 'present', 'presentation', 'previously', 'previous', 'primary', 'prior', 
    'problem', 'procedure', 'process', 'progress', 'progression', 'project', 'properly', 
    'proximal', 'put', 'quality', 'quadrant', 'quantity', 'rapidly', 'rarely', 'ray', 
    'read', 'reason', 'receive', 'recently', 'recent', 'recognize', 'record', 'recover', 
    'recovery', 'recurrence', 'red', 'reduce', 'reduced', 'reference', 'refer', 'region', 
    'regression', 'regimen', 'relative', 'relatively', 'relapse', 'remain', 'remarkable', 
    'remember', 'remission', 'repeat', 'report', 'require', 'resolution', 'respect', 
    'respectively', 'result', 'return', 'reveal', 'review', 'rich', 'right', 'rise', 
    'risk', 'role', 'rough', 'routine', 'run', 'succeed', 'suddenly', 'suffer', 
    'suggest', 'superior', 'superficial', 'successfully', 'seven', 'shall', 'show', 
    'should', 'side', 'sign', 'significant', 'significantly', 'similar', 'simple', 
    'since', 'single', 'sit', 'site', 'six', 'slightly', 'small', 'smooth', 'so', 
    'soft', 'some', 'sometimes', 'soon', 'speak', 'spontaneously', 'spot', 'square', 
    'stable', 'stage', 'stand', 'standard', 'start', 'state', 'status', 'stay', 'still', 
    'stop', 'story', 'strong', 'structure', 'study', 'subsequently', 'substance', 
    'successful', 'such', 'surface', 'surgery', 'symptom', 'system', 'systemic', 'take', 
    'talk', 'target', 'task', 'team', 'technique', 'ten', 'tertiary', 'test', 'than', 
    'that', 'the', 'their', 'then', 'therapy', 'thereafter', 'therefore', 'thick', 
    'thin', 'think', 'this', 'those', 'threat', 'through', 'thus', 'time', 'to', 'too', 
    'toward', 'total', 'transfer', 'treatment', 'try', 'turn', 'twice', 'two', 'type', 
    'typical', 'ultrasound', 'unable', 'unaware', 'unclear', 'under', 'undergo', 
    'understand', 'unfortunately', 'unilateral', 'unit', 'unknown', 'unless', 'unlike', 
    'unremarkable', 'until', 'unusual', 'upon', 'upper', 'usual', 'usually', 'value', 
    'various', 'very', 'via', 'visit', 'wall', 'walk', 'want', 'warm', 'was', 'way', 
    'weak', 'week', 'weekly', 'well', 'were', 'wet', 'what', 'when', 'where', 'which', 
    'while', 'white', 'who', 'why', 'will', 'wish', 'with', 'within', 'without', 'woman', 
    'word', 'work', 'worst', 'write', 'would', 'worsen', 'year', 'yellow', 'young', 'zone',

    # AGGIUNTE DALLA TOP FREQUENCY_TERMS.CSV (32 termini semanticamente meno rilevanti)
    # INCLUSO 'blood' (frequenza 4669) che è un descrittore generico/misura e non un reperto specifico.
    'admit', 'analysis', 'base', 'biopsy', 'blood', 'blood pressure', 'clinical', 
    'compute', 'compute tomography', 'count', 'detect', 'diagnose', 'due', 'emergency', 
    'fig', 'figure', 'image', 'intravenous', 'laboratory', 'magnetic', 
    'magnetic resonance', 'mri', 'oral', 'physical', 'pressure', 'rate', 'resonance', 
    'scan', 'size', 'surgical', 'tomography', 'underwent', 'weight', 'treat',
    'patient', 'low', 'use', 'chest', 'abdominal', 'female', 'admission', 'man',
    'cell', 'pain', 'three', 'first', 'area', 'severe', 'note', 'make', 'large', 'range',
    'second', 'loss', 'see', 'evaluation', 'identify', 'measure', 'condition', 'function',
    'improvement', 'consistent', 'four', 'control', 'remove', 'age', 'last', 'min', 'culture',
    'administer', 'several', 'addition', 'imaging', 'free', 'complaint', 'anti', 'room', 'response',
    'end'
}